name: Trigger auto deployment for businessconsultant

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/businessconsultant-AutoDeployTrigger-bce42340-976f-4d4e-a27a-bfc532f7e4ad.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BUSINESSCONSULTANT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BUSINESSCONSULTANT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BUSINESSCONSULTANT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.BUSINESSCONSULTANT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BUSINESSCONSULTANT_REGISTRY_PASSWORD }}
          containerAppName: businessconsultant
          resourceGroup: danishrg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


